# The Docker image that will be used to build your app
image: node:22-alpine
# Functions that should be executed before the build script is run
before_script:
  - npm install
pages:
  stage: build
  script:
    - free -m
    # Give Node more memory to work with
    - export NODE_OPTIONS="--max-old-space-size=3076"
    - npm run build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - dist
  publish: dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
